### ISSUE TITLE
Error when connecting with a wrong fingerprint

### ISSUE THREAD

**Issue by MiSchroe** [MiSchroe/klf-200-api#165]
```text
TypeError: Converting circular structure to JSON --> starting at object with constructor 'Object' --- property 'issuerCertificate' closes the circle at JSON.stringify (<anonymous>) at TLSSocket.loginErrorHandler (/opt/iobroker/node_modules/iobroker.klf200/node_modules/klf-200-api/dist/cjs/connection.js:324:70) at TLSSocket.emit (node:events:529:35) at emitErrorNT (node:internal/streams/destroy:151:8) at emitErrorCloseNT (node:internal/streams/destroy:116:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Error happens at https://github.com/MiSchroe/klf-200-api/blob/2239145f60efe2399a2313bb3bf16e63d37e474e/src/connection.ts#L784

Occurs, when you try to login with a wrong fingerprint during logging the error.

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the loginErrorHandler to avoid stringifying the entire error object, which can contain circular references from the TLS certificate. Instead, we now log a more specific error message.

I also created pull request: https://github.com/MiSchroe/klf-200-api/pull/166


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
